version: "3.7"

services: 

    # dataservice:
    #     image:
    #     command: 
    #     ports: 
    #     working_dir: 
    #     volumes: 
    #     environment: 

    # emqx:
    #     container_name: emqx
    #     image: emqx/emqx:v4.0.0
    #     ports: 
    #         - 1883:1883
    #         - 8083:8083
    #         - 8883:8883
    #         - 8084:8084
    #         - 18083:18083

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        ports: 
            - 1883:1883
            - 9001:9001

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports: 
            - 5672:5672
            - 15672:15672
        environment: 
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

    postgres:
        container_name: postgres
        image: wonderbear/thingspanel-postgres:v1
        restart: always
        ports: 
            - 5432:5432
        # volumes: 
            # - postgres-data:/var/lib/postgresql/data
            # - /Users/wonderbear/Programming/docker/thingspanel/postgres:/docker-entrypoint-initdb.d
            # - /home/wonderbear/Projects/docker/thingspanel/postgres:/docker-entrypoint-initdb.d
        environment: 
            POSTGRES_USER: guest
            POSTGRES_PASSWORD: guest
            POSTGRES_DB: thingspanel

    postgres-admin:
        container_name: postgres-admin
        image: adminer
        restart: always
        ports:
            - 8080:8080
        environment: 
            ADMINER_DEFAULT_SERVER: postgres

# volumes: 
#     postgres-data: 